18-rails-validations/dragons/config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :dragons
  resources :masters
  resources :abilities

  # THE BELOW DOES THE EXACT SAME AS ABOVE

  # # Get the interface to create a resource
  # get '/dragons/new', to: 'dragons#new'

  # # Creates a resource
  # post '/dragons/', to: 'dragons#create'

  # # Lists all the resources
  # get '/dragons/', to: 'dragons#index'

  # # Get the details of one dragon
  # get '/dragons/:id', to: 'dragons#show'

  # # Get the interface to edit a resource
  # get '/dragons/:id/edit', to: 'dragons#edit'

  # # Update a resource
  # patch '/dragons/:id', to: 'dragons#update'

  # # Delete a resource
  # delete '/dragons/:id', to: 'dragons#destroy'

end

18-rails-validations/dragons/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
 end

18-rails-validations/dragons/app/models/dragon.rb
class Dragon < ApplicationRecord
    belongs_to :master, optional: true
    has_many :dragon_abilities
    has_many :abilities, through: :dragon_abilities

    validates :name, presence: true
    validates :weight, numericality: { less_than_or_equal_to: 10000,  only_integer: true }
    validates_inclusion_of :height, :in => 3..100
    validates :abilities, length: { maximum: 3 }
end

18-rails-validations/dragons/app/models/master.rb
class Master < ApplicationRecord
    has_many :dragons, dependent: :destroy
    accepts_nested_attributes_for :dragons

    validates :name, length: { in: 3..10 }
    validates :email, email: true
end

18-rails-validations/dragons/app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController

    before_action :define_current_ability

    def create
        Ability.create(ability_params)
        redirect_to abilities_path
    end

    def index
        @abilities = Ability.all
    end

    def update
        @ability.update(ability_params)
        redirect_to @ability
    end

    def destroy
        @ability.destroy
        redirect_to abilities_path
    end


    def define_current_ability
        if params[:id]
            @ability = Ability.find(params[:id])
        else
            @ability = Ability.new
        end
    end

    def ability_params
        # Permits, returns the value, and throws an error if its not there
        ability = params.require(:ability)
        # Permits, returns the value, but does not throw error
        ability = params[:ability]
        ability.permit(:name)
    end

end

18-rails-validations/dragons/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

18-rails-validations/dragons/app/controllers/dragons_controller.rb
class DragonsController < ApplicationController

    before_action :define_current_dragon

    def create
        @dragon = Dragon.create(dragon_params)
        if @dragon.valid?
            redirect_to dragons_path
        else
            render json: { "message": @dragon.errors.messages }
        end
    end

    def update
        @dragon.update(dragon_params)
        if @dragon.valid?
            redirect_to dragons_path
        else
            render json: { "message": @dragon.errors.messages }
        end
    end


    def index
        @dragons = Dragon.all
    end

    def new 
        @masters = Master.all
    end

    def edit 
        @masters = Master.all
    end

    def destroy
        @dragon.destroy
        redirect_to dragons_path
    end


    def define_current_dragon
        if params[:id]
            @dragon = Dragon.find(params[:id])
        else
            @dragon = Dragon.new
        end
    end

    def dragon_params
        dragon_params = params.require(:dragon).permit(:name, :weight, :height, :image, :master_id, ability_ids: [])
    end

end

18-rails-validations/dragons/app/controllers/masters_controller.rb
class MastersController < ApplicationController 
    before_action :define_current_master
    
    def create
        Master.create(master_params)
        redirect_to masters_path
    end
    
    def index
        @masters = Master.all
    end
    
    def update
        @master.update(master_params)
        redirect_to @master
    end
    
    def destroy
        @master.destroy
        redirect_to masters_path
    end
    
    def define_current_master
        if params[:id]
            @master = Master.find(params[:id])
        else
            @master = Master.new
            @master.dragons.new
        end
    end
    
    def master_params
        params.require(:master).permit(:name, :email, dragons_attributes: [ [ :name, :weight, :height, :image, :id ] ] )
    end
end

18-rails-validations/dragons/app/helpers/abilities_helper.rb
module AbilitiesHelper
end

18-rails-validations/dragons/app/helpers/masters_helper.rb
module MastersHelper
end

18-rails-validations/dragons/app/helpers/show_helper.rb
module ShowHelper
end

18-rails-validations/dragons/app/views/dragons/_form.html.erb
<%= form_with model: @dragon do | form | %>
    <%= form.label 'Name'%>
    <%= form.text_field :name %>
    <br />
    <%= form.label 'Height'%>
    <%= form.text_field :height %>
    <br />
    <%= form.label 'Weight'%>
    <%= form.text_field :weight %>
    <br />
    <%= form.label 'Image'%>
    <%= form.text_field :image %>
    <br />
    <%= form.label 'Master'%>
    <%= form.collection_select :master_id, @masters, :id, :name %>
    <br />
    <%= form.label 'Abilities'%>
    <%= form.collection_check_boxes :ability_ids, Ability.all, :id, :name %>
    <br />
    <%= form.submit %>
<% end %>

18-rails-validations/dragons/app/views/dragons/edit.erb
<h1>Edit Dragon</h1>
<%= render 'form' %>

18-rails-validations/dragons/app/views/dragons/index.erb
<h1>Dragons</h1>
<ul>
<% @dragons.each do | dragon | %>
    <li><%= link_to dragon.name, dragon %> <%= link_to 'Edit', edit_dragon_path(dragon) %> <%= link_to 'Delete', dragon, method: :delete %></li>
<% end %>
</ul>

18-rails-validations/dragons/app/views/dragons/new.erb
<h1>Create Dragon</h1>
<%= render 'form' %>

18-rails-validations/dragons/app/views/dragons/show.erb
<h1><%= @dragon.name %></h1>
<p>Height: <%= @dragon.height%></p>
<p>Weight: <%= @dragon.weight%></p>
<p>Master: <%= link_to @dragon.master.name, @dragon.master %></p>
<p>Abilties</p>
<ul>
<% @dragon.abilities.each do | ability | %>
    <li><%= link_to ability.name, ability %></li>
<% end %>
</ul>
<p>Image: <%= image_tag(@dragon.image, size: "100x100") %></p>

18-rails-validations/dragons/app/views/masters/_form.html.erb
<%= form_with model: @master do | form | %>
    <div>
    <%= form.label 'Name'%>
    <%= form.text_field :name %>
    <%= form.label 'Email'%>
    <%= form.text_field :email %>
    </div>
    <%= form.fields_for :dragons do | dragon_form | %>
    <br/>
        <div>
        <%= dragon_form.label 'Name'%>
        <%= dragon_form.text_field :name %>
        <br />
        <%= dragon_form.label 'Height'%>
        <%= dragon_form.text_field :height %>
        <br />
        <%= dragon_form.label 'Weight'%>
        <%= dragon_form.text_field :weight %>
        <br />
        <%= dragon_form.label 'Image'%>
        <%= dragon_form.text_field :image %>
        <br />
        <%= dragon_form.label 'Abilities'%>
        <%= dragon_form.collection_check_boxes :ability_ids, Ability.all, :id, :name %>
        <br />
        </div>
    <% end %>
    <%= form.submit %>
<% end %>

18-rails-validations/dragons/app/views/masters/edit.erb
<h1>Edit Master</h1>
<%= render 'form' %>

18-rails-validations/dragons/app/views/masters/index.erb
<h1>Masters</h1>
<ul>
<% @masters.each do | master | %>
    <li><%= link_to master.name, master %> <%= link_to 'Edit', edit_master_path(master) %> <%= link_to 'Delete', master, method: :delete %></li>
<% end %>
</ul>

18-rails-validations/dragons/app/views/masters/new.erb
<h1>Create Master</h1>
<%= render 'form' %>

18-rails-validations/dragons/app/views/masters/show.erb
<h1><%= @master.name %></h1>
<small><%= @master.email %></small>
<ul>
<% @master.dragons.each do | dragon | %>
    <li><%= link_to dragon.name, dragon %></li>
<% end %>
</ul>